import { Dimensions, StyleSheet } from "react-native";
import { themas } from "../../global/themes";

export const style = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor:'black', 
    },
    boxTop: {
        paddingTop: 80,
        height: Dimensions.get('window').height / 3,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    boxMid: {
        height: Dimensions.get('window').height / 4,
        width: '100%',
        paddingHorizontal: 30,      
        marginTop: 20,
        alignItems: 'center',
    },
    boxBottom: {
        height: Dimensions.get('window').height / 6,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    bloco: {
        width: 200,
        height: 140,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black', 
        borderRadius: 15, 
        shadowColor: 'rgba(0, 0, 0, 0.1)', 
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    text: {
        fontFamily: 'Roboto_400Regular',
        fontWeight: 'bold',
        fontSize: 18,
        color:'white',
        marginTop: 10,
        marginBottom:70, 

    },
    textBottom: {
        fontSize: 14,
        color: themas.colors.gray,
    },
    button: {
        width: 130,
        height: 50,
        marginBottom: 60,
        backgroundColor: 'black',
        borderColor: themas.colors.primary, 
        borderRadius: 25,
        borderWidth: 2, 
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2, 
    },
    button1: {
        flexDirection: 'row',
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        width: 200,
        backgroundColor: 'black', 
        borderRadius: 30, 
        borderWidth: 2, 
        borderColor:themas.colors.primary,
        paddingHorizontal: 10,
    },
    button2: {
        flexDirection: 'row',
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        width: 200,
        backgroundColor: 'black',
        borderRadius: 30,
        borderWidth: 2,
        borderColor:themas.colors.primary,
        paddingHorizontal: 10,
    },
    logo1: {
        height: 40,
        width: 40,
        marginRight: 8, 
    },
    logo2: {
        height: 30,
        width: 30,
        marginRight:12,
    },
    buttonText1: {
        fontSize: 14,
        color: 'white', 
        fontWeight: '600',
        marginRight: 20,  
    },
    buttonText2: {
        fontSize: 14,
        color: 'white',
        fontWeight: '600',
    },
});
